# Generated by Django 3.2.7 on 2021-09-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("high_priority", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "completed"),
                            ("IN_PROGRESS", "in_progress"),
                        ],
                        default="IN_PROGRESS",
                        max_length=12,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
